name: Extract from FAIR Data Point

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths:
      - '*.groovy'

jobs:
  fdp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Extract from FDP
        run: |
          groovy extractFDP.groovy | tee datasets.ttl

      - name: Commit Turtle
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.ttl
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Extracted new data from the FAIR Data Point as Turtle'
              git push
          fi
